// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Comparer is an autogenerated mock type for the Comparer type
type Comparer struct {
	mock.Mock
}

// Compare provides a mock function with given fields: pattern, word
func (_m *Comparer) Compare(pattern []string, word []string) int {
	ret := _m.Called(pattern, word)

	var r0 int
	if rf, ok := ret.Get(0).(func([]string, []string) int); ok {
		r0 = rf(pattern, word)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
