// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// IDList is an autogenerated mock type for the IDList type
type IDList struct {
	mock.Mock
}

// GenerateID provides a mock function with given fields:
func (_m *IDList) GenerateID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RandomID provides a mock function with given fields:
func (_m *IDList) RandomID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RemoveID provides a mock function with given fields: _a0
func (_m *IDList) RemoveID(_a0 string) {
	_m.Called(_a0)
}
