// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// DirectoryReader is an autogenerated mock type for the DirectoryReader type
type DirectoryReader struct {
	mock.Mock
}

// GetFiles provides a mock function with given fields:
func (_m *DirectoryReader) GetFiles() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFullPathToFile provides a mock function with given fields: _a0
func (_m *DirectoryReader) GetFullPathToFile(_a0 string) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
