// Code generated by mockery v1.0.0
package mocks

import bucket "github.com/jasiu001/maestro/bucket"

import mock "github.com/stretchr/testify/mock"

// FileManager is an autogenerated mock type for the FileManager type
type FileManager struct {
	mock.Mock
}

// GenerateNewName provides a mock function with given fields:
func (_m *FileManager) GenerateNewName() {
	_m.Called()
}

// GetFileContent provides a mock function with given fields:
func (_m *FileManager) GetFileContent() ([]bucket.Bundle, error) {
	ret := _m.Called()

	var r0 []bucket.Bundle
	if rf, ok := ret.Get(0).(func() []bucket.Bundle); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bucket.Bundle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveContent provides a mock function with given fields: _a0
func (_m *FileManager) SaveContent(_a0 []bucket.Bundle) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]bucket.Bundle) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
